const fs = require('fs');  
const getRoute = [  
"import { NextResponse } from 'next/server'",  
"import { requireAuth } from '@/lib/auth/require-permission'",  
"import { createAdminClient } from '@/lib/supabase/admin'",  
"",  
"export async function GET() {",  
"  try {",  
"    const user = await requireAuth()",  
"    const admin = createAdminClient()",  
"",  
"    const { data, error } = await admin",  
"      .from('team_invitations')",  
"      .select(`",  
"        *,",  
"        team_invitation_assignments (",  
"          *,",  
"          stores (*)",  
"        )",  
"      `)",  
"      .eq('invited_by', user.id)",  
"      .eq('status', 'pending')",  
"",  
"    if (error) throw error",  
"",  
"    return NextResponse.json({ invitations: data || [] })",  
"  } catch (error) {",  
"    const message = error instanceof Error ? error.message : 'FETCH_INVITATIONS_FAILED'",  
"    return NextResponse.json({ error: message }, { status: 500 })",  
"  }",  
"}",  
].join('\n');  
const deleteRoute = [  
"import { NextResponse } from 'next/server'",  
"import { requireAuth } from '@/lib/auth/require-permission'",  
"import { createAdminClient } from '@/lib/supabase/admin'",  
"",  
"export async function DELETE(",  
"  _request: Request,",  
"  { params }: { params: { id: string } }",  
") {",  
"  try {",  
"    const user = await requireAuth()",  
"    const admin = createAdminClient()",  
"",  
"    const { data, error } = await admin",  
"      .from('team_invitations')",  
"      .update({ status: 'revoked' })",  
"      .eq('id', params.id)",  
"      .eq('invited_by', user.id)",  
"      .select()",  
"",  
"    if (error) throw error",  
"    if (!data || data.length === 0) {",  
"      return NextResponse.json({ error: 'NOT_FOUND_OR_UNAUTHORIZED' }, { status: 404 })",  
"    }",  
"",  
"    return NextResponse.json({ invitation: data[0] })",  
"  } catch (error) {",  
"    const message = error instanceof Error ? error.message : 'REVOKE_INVITATION_FAILED'",  
"    return NextResponse.json({ error: message }, { status: 500 })",  
"  }",  
"}",  
].join('\n');  
fs.writeFileSync('app/api/team/invitations/route.ts', getRoute);  
fs.writeFileSync('app/api/team/invitations/[id]/route.ts', deleteRoute);  
